config/routes.rb
SportsOdds::Application.routes.draw do
  devise_for :users

  root 'events#index'

  resources :espn_games do
    collection do
      get :previews
    end
  end  

  resources :events do
    collection do
      get :nba
      get :mlb
      get :previews
    end
  end

  resources :admin do
    collection do
      get :previews_rules
    end
  end
  resources :pitchers do
    collection do
      get :today_games_pitchers
      get :update_stats
    end
  end
  resources :previews_rules

  resources :mlb do
    collection do
      get :index
      get :mlb_picks
    end
  end
  get 'mlb/mlb-picks/:id' => 'mlb#mlb_picks'

  resources :pages do
    collection do
      get :premium_picks
    end
  end
  get '/premium_picks' => 'pages#premium_picks'

end

app/models/pitcher.rb
class Pitcher < ActiveRecord::Base
	attr_accessible :name, :url, :throws, :age, :full_name
	has_many :pitcher_season_totals
	has_many :pitcher_platoon_splits
	has_many :pitcher_home_away
end

app/controllers/pitchers_controller.rb
class PitchersController < ApplicationController
  before_action :set_pitcher, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!
  layout "admin"

  # GET /pitchers
  # GET /pitchers.json
  def index
    @pitchers = Pitcher.all.order('name ASC').paginate(:page => params[:page], :per_page => 10)
  end

  # GET /pitchers/1
  # GET /pitchers/1.json
  def show
  end

  # GET /pitchers/new
  def new
    @pitcher = Pitcher.new
  end

  # GET /pitchers/1/edit
  def edit
  end

  # POST /pitchers
  # POST /pitchers.json
  def create
    @pitcher = Pitcher.new(pitcher_params)

    respond_to do |format|
      if @pitcher.save
        format.html { redirect_to @pitcher, notice: 'Pitcher was successfully created.' }
        format.json { render action: 'show', status: :created, location: @pitcher }
      else
        format.html { render action: 'new' }
        format.json { render json: @pitcher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pitchers/1
  # PATCH/PUT /pitchers/1.json
  def update
    respond_to do |format|
      if @pitcher.update(pitcher_params)
        format.html { redirect_to @pitcher, notice: 'Pitcher was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @pitcher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pitchers/1
  # DELETE /pitchers/1.json
  def destroy
    @pitcher.destroy
    respond_to do |format|
      format.html { redirect_to pitchers_url }
      format.json { head :no_content }
    end
  end

  def today_games_pitchers
    @date = Date.today
    @espn_games = EspnGame.select("pitcher_a,pitcher_h").where(:date => @date).order('time ASC')
    @pitcher_ids = Array.new
    @espn_games.each do |espn_game|
      @pitcher_ids.push(espn_game.pitcher_a) unless @pitcher_ids.include?(espn_game.pitcher_a)
      @pitcher_ids.push(espn_game.pitcher_h) unless @pitcher_ids.include?(espn_game.pitcher_h)
    end  
    @pitchers = Pitcher.where("id in (?)", @pitcher_ids).paginate(:page => params[:page], :per_page => 10)
  end  

  def update_stats
    %x[rake populate_pitchers_stats]
    flash[:notice] = 'Pitchers statistics have been updated succesfully'
    redirect_to "/pitchers"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pitcher
      @pitcher = Pitcher.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pitcher_params
      params[:pitcher]
    end
end

app/helpers/pitchers_helper.rb
module PitchersHelper
end

app/views/pitchers/_form.html.erb
<%= form_for @pitcher, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :url, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :url, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                pitchers_path, :class => 'btn' %>
  </div>
<% end %>

app/views/pitchers/edit.html.erb
<%- model_class = Pitcher -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/pitchers/index.html.erb
<%- model_class = Pitcher -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<a href="/pitchers/update_stats"><button class="btn">Update Stats</button></a>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:url) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @pitchers.each do |pitcher| %>
      <tr>
        <td><%= link_to pitcher.id, pitcher_path(pitcher) %></td>
        <td><%= pitcher.name %></td>
        <td><%= pitcher.url %></td>
        <td><%=l pitcher.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_pitcher_path(pitcher), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      pitcher_path(pitcher),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @pitchers %>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_pitcher_path,
            :class => 'btn btn-primary' %>

app/views/pitchers/new.html.erb
<%- model_class = Pitcher -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/pitchers/show.html.erb
<%- model_class = Pitcher -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @pitcher.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:url) %>:</strong></dt>
  <dd><%= @pitcher.url %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              pitchers_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_pitcher_path(@pitcher), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              pitcher_path(@pitcher),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/pitchers/today_games_pitchers.html.erb
<%- model_class = Pitcher -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:url) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @pitchers.each do |pitcher| %>
      <tr>
        <td><%= link_to pitcher.id, pitcher_path(pitcher) %></td>
        <td><%= pitcher.name %></td>
        <td><%= pitcher.url %></td>
        <td><%=l pitcher.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_pitcher_path(pitcher), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      pitcher_path(pitcher),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @pitchers %>