config/routes.rb
SportsOdds::Application.routes.draw do
  devise_for :users

  root 'events#index'

  resources :espn_games do
    collection do
      get :previews
    end
  end  

  resources :events do
    collection do
      get :nba
      get :mlb
      get :previews
    end
  end

  resources :admin do
    collection do
      get :previews_rules
    end
  end
  resources :pitchers do
    collection do
      get :today_games_pitchers
      get :update_stats
    end
  end
  resources :previews_rules

  resources :mlb do
    collection do
      get :index
      get :mlb_picks
    end
  end
  get 'mlb/mlb-picks/:id' => 'mlb#mlb_picks'

  resources :pages do
    collection do
      get :premium_picks
    end
  end
  get '/premium_picks' => 'pages#premium_picks'

end

app/models/espn_game.rb
class EspnGame < ActiveRecord::Base
	attr_accessible :pitcher_a, :pitcher_h, :time, :date, :team_a, :team_h, :game_id
	belongs_to :games
end

app/controllers/espn_games_controller.rb
class EspnGamesController < ApplicationController
  before_action :set_espn_game, only: [:show, :edit, :update, :destroy]
  helper_method :check_condition
  layout "wp_application"

  # GET /espn_games
  # GET /espn_games.json
  def index
    if params[:date].present?
      @date = params[:date]
    else
      @date = Date.today
    end
    @espn_games = EspnGame.where(:date => @date).order('time ASC')
  end

  # GET /espn_games/1
  # GET /espn_games/1.json
  def show
  end

  # GET /espn_games/new
  def new
    @espn_game = EspnGame.new
  end

  # GET /espn_games/1/edit
  def edit
  end

  # POST /espn_games
  # POST /espn_games.json
  def create
    @espn_game = EspnGame.new(espn_game_params)

    respond_to do |format|
      if @espn_game.save
        format.html { redirect_to @espn_game, notice: 'Espn game was successfully created.' }
        format.json { render action: 'show', status: :created, location: @espn_game }
      else
        format.html { render action: 'new' }
        format.json { render json: @espn_game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /espn_games/1
  # PATCH/PUT /espn_games/1.json
  def update
    respond_to do |format|
      if @espn_game.update(espn_game_params)
        format.html { redirect_to @espn_game, notice: 'Espn game was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @espn_game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /espn_games/1
  # DELETE /espn_games/1.json
  def destroy
    @espn_game.destroy
    respond_to do |format|
      format.html { redirect_to espn_games_url }
      format.json { head :no_content }
    end
  end

  def previews
    if params[:game].present?
      @game   = EspnGame.find(params[:game])
      #Teams Stats
      @team_a = EspnTeam.find(@game.team_a)
      @team_h = EspnTeam.find(@game.team_h)
      #Pitchers Stats
      # @game.pitcher_a = 116
      # @game.pitcher_h = 116
      @pitcher_a = Pitcher.find(@game.pitcher_a)
      @pitcher_h = Pitcher.find(@game.pitcher_h)

      #Previews Rules
      @team_previews_rules    = PreviewsRule.all.where("rule_for='Team'")
      @pitcher_previews_rules = PreviewsRule.all.where("rule_for='Pitcher'")

      #Odds
      events = Event.where("DATE(event_datetime) = ? AND league = 'MLB'",@game.date)
      events.each do |event|
        if(event.participants.first.participant_name.include? @team_a.name) || (event.participants.last.participant_name.include? @team_h.name)
          @event = event
        end  
      end

      @title  = "#{@team_h.name} VS #{@team_a.name} Perdiction - #{params[:date]}"
      set_meta_tags :title => @title
      set_meta_tags :description => "100% Free Betting Advice. #{@team_a.name} vs #{@team_h.name} Prediction Against The Spread, Totals and Moneyline plays."
      render :layout => "previews"
    else
      redirect_to "/espn_games"
    end  
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_espn_game
      @espn_game = EspnGame.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def espn_game_params
      params[:espn_game]
    end    
end

app/helpers/espn_games_helper.rb
module EspnGamesHelper
end

app/views/espn_games/_espn_games.html.erb
<p>Date: <input type="text" id="datepicker"></p>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Date/Time</th>
      <th>Teams</th>
      <th>Pitchers</th>
      <th>Perdictions</th>
    </tr>
  </thead>

  <tbody>
    <% @espn_games.each do |game| %>
      <tr>
        <td><%= game.time %></td>
        <td>
          <%= EspnTeam.find(game.team_h).name %><br/>
          <%= EspnTeam.find(game.team_a).name %>
        </td>
        <td>
          <%= Pitcher.find(game.pitcher_h).name %><br/>
          <%= Pitcher.find(game.pitcher_a).name %>
        </td>
        <%
        if(game.date >= Date.today)
        %>
        <% date = (game.date - 1.hours).strftime("%d %b, %Y") %>
        <td><a href="espn_games/previews?game=<%= game.id %>&date=<%= date %>" class="perdiction">Predictions</a></td>
        <%
        else
          "<td></td>"
        end  
        %>  
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<script>
  $(function() {
    $('#datepicker').datepicker().on('changeDate', function(ev) {
      var d = new Date(ev.date)
      
      var day = d.getDate();
      var month = d.getMonth()+1;
      var year = d.getFullYear();

      var date = year +"-"+ month  +"-"+ day; 

      window.location = location.origin + location.pathname + "?date=" + date;
      $(this).datepicker('hide');
    });
  });

  var today = new Date();
  var dd = today.getDate();
  var mm = today.getMonth()+1; //January is 0!
  var yyyy = today.getFullYear();

  if(dd<10) {
      dd='0'+dd
  } 

  if(mm<10) {
      mm='0'+mm
  } 

  today = yyyy+'-'+dd+'-'+mm;
  var DATE = location.search.split('date=')[1] ? location.search.split('date=')[1] : today;
  $("#datepicker").val(DATE);
  </script>

app/views/espn_games/_form.html.erb
<%= form_for(@espn_game) do |f| %>
  <% if @espn_game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@espn_game.errors.count, "error") %> prohibited this espn_game from being saved:</h2>

      <ul>
      <% @espn_game.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/espn_games/edit.html.erb
<h1>Editing espn_game</h1>

<%= render 'form' %>

<%= link_to 'Show', @espn_game %> |
<%= link_to 'Back', espn_games_path %>

app/views/espn_games/index.html.erb
<div class="tabbable tabs-below" id="content">
  <ul class="nav nav-tabs">
    <li class="active"><a href="#A" data-toggle="tab">Espn Games</a></li>
  </ul>
  <div class="tab-content">
    <div class="tab-pane active" id="A">
      <%= render :partial => "espn_games/espn_games", :locals =>  { :events => @events } %>
    </div>
  </div>
</div>

app/views/espn_games/new.html.erb
<h1>New espn_game</h1>

<%= render 'form' %>

<%= link_to 'Back', espn_games_path %>

app/views/espn_games/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_espn_game_path(@espn_game) %> |
<%= link_to 'Back', espn_games_path %>