config/routes.rb
SportsOdds::Application.routes.draw do
  devise_for :users

  root 'events#index'

  resources :espn_games do
    collection do
      get :previews
    end
  end  

  resources :events do
    collection do
      get :nba
      get :mlb
      get :previews
    end
  end

  resources :admin do
    collection do
      get :previews_rules
    end
  end
  resources :pitchers do
    collection do
      get :today_games_pitchers
      get :update_stats
    end
  end
  resources :previews_rules

  resources :mlb do
    collection do
      get :index
      get :mlb_picks
    end
  end
  get 'mlb/mlb-picks/:id' => 'mlb#mlb_picks'

  resources :pages do
    collection do
      get :premium_picks
    end
  end
  get '/premium_picks' => 'pages#premium_picks'

end

app/models/previews_rule.rb
class PreviewsRule < ActiveRecord::Base
	attr_accessible :rule_for, :split, :column, :operator1, :value1, :operator2, :value2, :statement
end

app/controllers/previews_rules_controller.rb
class PreviewsRulesController < ApplicationController
  before_action :set_previews_rule, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!
  layout "admin"

  # GET /previews_rules
  # GET /previews_rules.json
  def index
    @previews_rules = PreviewsRule.all
  end

  # GET /previews_rules/1
  # GET /previews_rules/1.json
  def show
  end

  # GET /previews_rules/new
  def new
    @previews_rule = PreviewsRule.new
    #Rules For
    @rules_for = {
      'Team'  => 'Team', 'Pitcher'   => 'Pitcher'
    }
    #Splits for Dropdown
    @splits = EspnTeamStat.select("split").where("split != 'record-position'").group("split")
    @split_list = Hash.new
    @splits.each do |split|
      @split_list[split.split] = split.split
    end
    @split_list['vs RHB'] = 'vs RHB'
    @split_list['vs LHB'] = 'vs LHB'
    #Column for Dropdown
    @column = {
      'G' => 'G', 'GS'  => 'GS', 'R'   => 'R', 'BA'  => 'BA', 'OBP' => 'OBP', 'SLG' => 'SLG',
      'W' => 'W', 'L' => 'L', 'W_L' => 'W_L', 'ERA' => 'ERA', 'GF' => 'GF', 'CG' => 'CG', 'SHO' => 'SHO', 'SV' => 'SV', 'IP' => 'IP', 'H' => 'H', 'ER' => 'ER', 'HR' => 'HR', 'BB' => 'BB', 'IBB' => 'IBB', 'SO' => 'SO', 'HBP' => 'HBP', 'BK' => 'BK', 'WP' => 'WP', 'BF' => 'BF', 'WHIP' => 'WHIP', 'SOp' => 'SO9', 
      'BA' => 'BA',
      'R/GS' => 'R/GS'
    }
    #Operators for Dropdown
    @operators = {
      '<'  => '<', '<='   => '<=', '>'  => '>', '>=' => '>=', '=' => '='
    }
  end

  # GET /previews_rules/1/edit
  def edit
    #Rules For
    @rules_for = {
      'Team'  => 'Team', 'Pitcher'   => 'Pitcher'
    }
    #Splits for Dropdown
    @splits = EspnTeamStat.select("split").where("split != 'record-position'").group("split")
    @split_list = Hash.new
    @splits.each do |split|
      @split_list[split.split] = split.split
    end
    @split_list['vs RHB'] = 'vs RHB'
    @split_list['vs LHB'] = 'vs LHB'
    #Column for Dropdown
    @column = {
      'G' => 'G', 'GS'  => 'GS', 'R'   => 'R', 'BA'  => 'BA', 'OBP' => 'OBP', 'SLG' => 'SLG',
      'W' => 'W', 'L' => 'L', 'W_L' => 'W_L', 'ERA' => 'ERA', 'GF' => 'GF', 'CG' => 'CG', 'SHO' => 'SHO', 'SV' => 'SV', 'IP' => 'IP', 'H' => 'H', 'ER' => 'ER', 'HR' => 'HR', 'BB' => 'BB', 'IBB' => 'IBB', 'SO' => 'SO', 'HBP' => 'HBP', 'BK' => 'BK', 'WP' => 'WP', 'BF' => 'BF', 'WHIP' => 'WHIP', 'SOp' => 'SOp', 
      'BA' => 'BA',
      'R/GS' => 'R/GS'
    }
    #Operators for Dropdown
    @operators = {
      '<'  => '<', '<='   => '<=', '>'  => '>', '>=' => '>=', '=' => '='
    }
  end

  # POST /previews_rules
  # POST /previews_rules.json
  def create
    @previews_rule = PreviewsRule.new(previews_rule_params)

    respond_to do |format|
      if @previews_rule.save
        format.html { redirect_to @previews_rule, notice: 'Previews rule was successfully created.' }
        format.json { render action: 'show', status: :created, location: @previews_rule }
      else
        format.html { render action: 'new' }
        format.json { render json: @previews_rule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /previews_rules/1
  # PATCH/PUT /previews_rules/1.json
  def update
    respond_to do |format|
      if @previews_rule.update(previews_rule_params)
        format.html { redirect_to @previews_rule, notice: 'Previews rule was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @previews_rule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /previews_rules/1
  # DELETE /previews_rules/1.json
  def destroy
    @previews_rule.destroy
    respond_to do |format|
      format.html { redirect_to previews_rules_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_previews_rule
      @previews_rule = PreviewsRule.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def previews_rule_params
      params[:previews_rule]
    end
end

app/helpers/previews_rule_helper.rb
module PreviewsRuleHelper
end

app/helpers/previews_rules_helper.rb
module PreviewsRulesHelper
end

app/views/previews_rules/_form.html.erb
<%= form_for @previews_rule, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :rule_for, :class => 'control-label' %>
    <div class="controls">
      <%= f.select(:rule_for, @rules_for) %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :split, :class => 'control-label' %>
    <div class="controls">
      <%= f.select(:split, @split_list) %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :column, :class => 'control-label' %>
    <div class="controls">
      <%= f.select(:column, @column) %>
    </div>
  </div>
  <div class="control-group">
    <div class="controls" style="margin-left: 100px;">
      <h4>Condition 1</h4>
    </div>  
    <div class="controls" style="float:left">
      <p>Value</p>
      <%= f.text_field :value1, :class => 'text_field' %>
    </div>  
    <div class="controls" style="float:left; margin-left: 25px;">
      <p>Operator</p>
      <%= f.select(:operator1, @operators) %>
    </div>
  </div>
  <div class="control-group">
    <div class="controls" style="margin-left: 100px;">
      <h4>Condition 2 (And)</h4>
    </div>  
    <div class="controls" style="float:left">
      <p>Value</p>
      <%= f.text_field :value2, :class => 'text_field' %>
    </div>  
    <div class="controls" style="float:left; margin-left: 25px;">
      <p>Operator</p>
      <%= f.select(:operator2, @operators) %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :statement, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :statement, :class => 'text_field', :style => 'width:450px; height:100px;'%>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                previews_rules_path, :class => 'btn' %>
  </div>
<% end %>

app/views/previews_rules/edit.html.erb
<%- model_class = PreviewsRule -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/previews_rules/index.html.erb
<%- model_class = PreviewsRule -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:rule_for) %></th>
      <th><%= model_class.human_attribute_name(:split) %></th>
      <th><%= model_class.human_attribute_name(:column) %></th>
      <th><%= model_class.human_attribute_name(:value1) %></th>
      <th><%= model_class.human_attribute_name(:operator1) %></th>
      <th><%= model_class.human_attribute_name(:operator2) %></th>
      <th><%= model_class.human_attribute_name(:value2) %></th>
      <th><%= model_class.human_attribute_name(:statement) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @previews_rules.each do |previews_rule| %>
      <tr>
        <td><%= link_to previews_rule.id, previews_rule_path(previews_rule) %></td>
        <td><%= previews_rule.rule_for %></td>
        <td><%= previews_rule.split %></td>
        <td><%= previews_rule.column %></td>
        <td><%= previews_rule.value1 %></td>
        <td><%= previews_rule.operator1 %></td>
        <td><%= previews_rule.operator2 %></td>
        <td><%= previews_rule.value2 %></td>
        <td><%= previews_rule.statement %></td>
        <td><%=l previews_rule.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_previews_rule_path(previews_rule), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      previews_rule_path(previews_rule),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_previews_rule_path,
            :class => 'btn btn-primary' %>

app/views/previews_rules/new.html.erb
<%- model_class = PreviewsRule -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/previews_rules/show.html.erb
<%- model_class = PreviewsRule -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:split) %>:</strong></dt>
  <dd><%= @previews_rule.split %></dd>
  <dt><strong><%= model_class.human_attribute_name(:column) %>:</strong></dt>
  <dd><%= @previews_rule.column %></dd>
  <dt><strong><%= model_class.human_attribute_name(:operator1) %>:</strong></dt>
  <dd><%= @previews_rule.operator1 %></dd>
  <dt><strong><%= model_class.human_attribute_name(:value1) %>:</strong></dt>
  <dd><%= @previews_rule.value1 %></dd>
  <dt><strong><%= model_class.human_attribute_name(:statement) %>:</strong></dt>
  <dd><%= @previews_rule.statement %></dd>
  <dt><strong><%= model_class.human_attribute_name(:operator2) %>:</strong></dt>
  <dd><%= @previews_rule.operator2 %></dd>
  <dt><strong><%= model_class.human_attribute_name(:value2) %>:</strong></dt>
  <dd><%= @previews_rule.value2 %></dd>
  <dt><strong><%= model_class.human_attribute_name(:rule_for) %>:</strong></dt>
  <dd><%= @previews_rule.rule_for %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              previews_rules_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_previews_rule_path(@previews_rule), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              previews_rule_path(@previews_rule),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>