config/routes.rb
SportsOdds::Application.routes.draw do
  devise_for :users

  root 'events#index'

  resources :espn_games do
    collection do
      get :previews
    end
  end  

  resources :events do
    collection do
      get :nba
      get :mlb
      get :previews
    end
  end

  resources :admin do
    collection do
      get :previews_rules
    end
  end
  resources :pitchers do
    collection do
      get :today_games_pitchers
      get :update_stats
    end
  end
  resources :previews_rules

  resources :mlb do
    collection do
      get :index
      get :mlb_picks
    end
  end
  get 'mlb/mlb-picks/:id' => 'mlb#mlb_picks'

  resources :pages do
    collection do
      get :premium_picks
    end
  end
  get '/premium_picks' => 'pages#premium_picks'

end

app/models/espn_game.rb
class EspnGame < ActiveRecord::Base
	attr_accessible :pitcher_a, :pitcher_h, :time, :date, :team_a, :team_h, :game_id
	belongs_to :games
end

app/models/espn_team.rb
class EspnTeam < ActiveRecord::Base
	attr_accessible :name, :url
	has_many :espn_team_stats
end

app/models/espn_team_stat.rb
class EspnTeamStat < ActiveRecord::Base
	belongs_to :espn_team
	attr_accessible :split, :G, :GS, :R, :BA, :OBP, :SLG, :record, :position, :espn_team_id
end

app/models/event.rb
class Event < ActiveRecord::Base
	has_many :participants
	has_many :periods
	attr_accessible :event_datetime, :gamenumber, :sporttype, :league, :is_live
end

app/models/odd.rb
class Odd < ActiveRecord::Base
	belongs_to :participant
	attr_accessible :moneyline_value, :to_base, :participant_id
end

app/models/participant.rb
class Participant < ActiveRecord::Base
	belongs_to :event
	has_one :odd
	attr_accessible :participant_name, :contestantnum, :rotnum, :visiting_home_draw, :event_id, :pitcher
end

app/models/period.rb
class Period < ActiveRecord::Base
	belongs_to :event
	attr_accessible :event_id, :period_number, :period_description, :periodcutoff_datetime, :period_status, :period_update, :spread_maximum, :moneyline_maximum, :total_maximum, :moneyline_visiting, :moneyline_home, :spread_visiting, :spread_adjust_visiting, :spread_home, :spread_adjust_home, :tootal_point, :over_adjust, :under_adjust
end

app/models/pitcher.rb
class Pitcher < ActiveRecord::Base
	attr_accessible :name, :url, :throws, :age, :full_name
	has_many :pitcher_season_totals
	has_many :pitcher_platoon_splits
	has_many :pitcher_home_away
end

app/models/pitcher_home_away.rb
class PitcherHomeAway < ActiveRecord::Base
	belongs_to :pitcher
	attr_accessible :split, :W, :L, :ERA, :GS, :WHIP, :pitcher_id
end

app/models/previews_rule.rb
class PreviewsRule < ActiveRecord::Base
	attr_accessible :rule_for, :split, :column, :operator1, :value1, :operator2, :value2, :statement
end

app/models/stat_rank.rb
class StatRank < ActiveRecord::Base
	belongs_to :team_stat
	attr_accessible :at_bats, :runs_scored, :hits, :double_hit, :triple_hit, :home_run, :stolen_base, :caught_stealing, :bases_balls, :strikeout, :ba, :obp, :slg, :ops, :total_bases, :hbp, :sf, :team_stat_id
end

app/models/team_stat.rb
class TeamStat < ActiveRecord::Base
	belongs_to :espn_team
	has_one :stat_rank
	attr_accessible :game_played, :runs_scored, :hits, :obp, :slg, :reacord, :position, :espn_team_id
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
 		attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/mlb_controller.rb
class MlbController < ApplicationController
  helper_method :check_condition
  layout "wp_application"


  def index
    # if params[:date].present?
    #   @date = params[:date]
    # else
      @date = Date.today
    # end
    @espn_games = EspnGame.where(:date => @date).order('TIME(time) ASC')  	
	render :layout => "2_column"
  end	

  def mlb_picks
  	if(params[:id].present?)
  		#parmters from url
  		url    = params[:id]
  		params = url.split("-predictions-")
  		if(params.first.include? "-vs-")
	  		teams  = params.first.split("-vs-")
	  		team_a = teams.first
	  		team_b = teams.last
	  	end	

		begin
	  		date   = Date::strptime(params.last, "%Y-%d-%m")
		rescue ArgumentError
			date = nil
		end
		if(team_a.nil? || team_b.nil? || date.nil?)
	  		redirect_to "/"
		end

		#Get Game
		@team_a = EspnTeam.where("name LIKE '%#{team_a}%'").first
		@team_b = EspnTeam.where("name LIKE '%#{team_b}%'").first
		if(@team_a.present? && @team_b.present?)
			@game = EspnGame.where("((team_a = ? AND team_h = ?) OR (team_a = ? AND team_h = ?)) AND date = ?",@team_a.id,@team_b.id,@team_b.id,@team_a.id,date).first
			if(@game.present?)
		      #Teams Stats
		      @team_a = EspnTeam.find(@game.team_a)
		      @team_h = EspnTeam.find(@game.team_h)
		      #Pitchers Stats
		      # @game.pitcher_a = 116
		      # @game.pitcher_h = 116
		      @pitcher_a = Pitcher.find(@game.pitcher_a)
		      @pitcher_h = Pitcher.find(@game.pitcher_h)

		      #Previews Rules
		      @team_previews_rules    = PreviewsRule.all.where("rule_for='Team'")
		      @pitcher_previews_rules = PreviewsRule.all.where("rule_for='Pitcher'")

		      #Odds
		      events = Event.where("DATE(event_datetime) = ? AND league = 'MLB'",@game.date)
		      events.each do |event|
		        if(event.participants.first.participant_name.include? @team_a.name) || (event.participants.last.participant_name.include? @team_h.name)
		          @event = event
		        end  
		      end
		      #binding.pry

		      @title  = "#{@team_h.name} VS #{@team_a.name} Perdiction - #{date}"
		      set_meta_tags :title => @title
		      set_meta_tags :description => "100% Free Betting Advice. #{@team_a.name} vs #{@team_h.name} Prediction Against The Spread, Totals and Moneyline plays."
		      render :layout => "1_column"
		  	else
		  		redirect_to "/"
			end			
	  	else
	  		redirect_to "/"
		end	
  	else
  		redirect_to "/"
  	end		
  end 	 	

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/espn_games_helper.rb
module EspnGamesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/mlb_helper.rb
module MlbHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pitchers_helper.rb
module PitchersHelper
end

app/views/admin/previews_rules.html.erb
<%= form_for @previews_rules, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :url, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :url, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                pitchers_path, :class => 'btn' %>
  </div>
<% end %>

app/views/layouts/1_column.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <%= display_meta_tags %>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta property="og:image" content="http://www.sharpnation.com/wp-content/uploads/2013/11/thunder-150x150.jpg">

    <title><%= content_for?(:title) ? yield(:title) : "SportsOdds" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <!--[if lt IE 9]>
    <link rel="stylesheet" type="text/css" href="http://www.sharpnation.com/wp-content/themes/hottopix/css/iecss.css" />
    <![endif]-->

    <!--[if IE]>
    <link rel='stylesheet' id='mailchimpSF_ie_css-css'  href='http://www.sharpnation.com/wp-content/plugins/mailchimp/css/ie.css?ver=3.7.3' type='text/css' media='all' />
    <![endif]-->
    <link rel="stylesheet" id="googlefonts-css" href="http://fonts.googleapis.com/css?family=Open+Sans%3A400%2C600%2C700%7COpen+Sans+Condensed%3A300%2C700%7COswald%3A300%2C400%2C700%7CAlegreya%3A400&amp;subset=latin%2Clatin-ext%2Ccyrillic%2Ccyrillic-ext%2Cgreek-ext%2Cgreek%2Cvietnamese&amp;ver=3.7.3" type="text/css" media="all">




    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= stylesheet_link_tag "reset", :media => "all" %>
    <%= stylesheet_link_tag "wp_style", :media => "all" %>
    <%= stylesheet_link_tag "custom", :media => "all" %>
    <%= stylesheet_link_tag "jquery-ui-1.10.4.min.css" %>
    <link rel="stylesheet" id="googlefonts-css" href="http://fonts.googleapis.com/css?family=Open+Sans%3A400%2C600%2C700%7COpen+Sans+Condensed%3A300%2C700%7COswald%3A300%2C400%2C700%7CAlegreya%3A400&amp;subset=latin%2Clatin-ext%2Ccyrillic%2Ccyrillic-ext%2Cgreek-ext%2Cgreek%2Cvietnamese&amp;ver=3.7.3" type="text/css" media="all">

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
    <%= javascript_include_tag "application" %>
  </head>
  <body>
    <div id="site">
      <div id="wrapper">
        <div id="header-wrapper">
          <div id="top-header-wrapper">
            <div id="top-nav">
              <div class="menu-top-container">
                <ul id="menu-top" class="menu">
                  <li id="menu-item-1097" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1097">
                    <a href="http://www.sharpnation.com/become-writer/">Write For SharpNation</a>
                  </li>
                </ul>
              </div>
            </div><!--top-nav-->
            <div id="content-social">
              <ul>
                <li><a href="http://www.facebook.com/sharpnation" alt="Facebook" class="fb-but" target="_blank"></a></li>
                <li><a href="http://www.twitter.com/SharpNationNews" alt="Twitter" class="twitter-but" target="_blank"></a></li>
                <li><a href="https://plus.google.com/+sharpnation" alt="Google Plus" class="google-but" target="_blank"></a></li>
                <li><a href="http://www.sharpnation.com/feed/rss/" alt="RSS Feed" class="rss-but"></a></li>
              </ul>
            </div><!--content-social-->
          </div><!--top-header-wrapper-->
          
          <div id="logo-wrapper" itemscope="" itemtype="http://schema.org/Organization">
            <a itemprop="url" href="assets/Free Sports Picks -.html"><img itemprop="logo" src="<%= asset_path('sharpnation.png')%>" alt="Free Sports Picks"></a>
            <form action="#" class="aright" id="login_form">
              <div class="box aleft">
                <span>Username:</span><br/><input type="text" id="username" name="username" value=""/>
              </div>
              <div class="box aleft">
                <span>Password:</span><br/><input type="password" id="password" name="password" value=""/>
              </div>  
              <input type="submit" value="Login" class="login" onclick="return false;" />
            </form>
          </div><!--logo-wrapper-->
        </div><!--header-wrapper-->
        
        <div id="nav-wrapper">

          <%= render :partial => "layouts/menu" %>

        </div><!--nav-wrapper-->

        <div id="main">
                  
          <div id="content-wrapper">
            <div id="home-main" style="width:100%">

              <%= yield %>

            </div><!--home-main-->
          </div>
        </div>
      </div>
    </div>  
  </body>
</html>

app/views/layouts/2_column.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <%= display_meta_tags %>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta property="og:image" content="http://www.sharpnation.com/wp-content/uploads/2013/11/thunder-150x150.jpg">

    <title><%= content_for?(:title) ? yield(:title) : "SportsOdds" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <!--[if lt IE 9]>
    <link rel="stylesheet" type="text/css" href="http://www.sharpnation.com/wp-content/themes/hottopix/css/iecss.css" />
    <![endif]-->

    <!--[if IE]>
    <link rel='stylesheet' id='mailchimpSF_ie_css-css'  href='http://www.sharpnation.com/wp-content/plugins/mailchimp/css/ie.css?ver=3.7.3' type='text/css' media='all' />
    <![endif]-->
    <link rel="stylesheet" id="googlefonts-css" href="http://fonts.googleapis.com/css?family=Open+Sans%3A400%2C600%2C700%7COpen+Sans+Condensed%3A300%2C700%7COswald%3A300%2C400%2C700%7CAlegreya%3A400&amp;subset=latin%2Clatin-ext%2Ccyrillic%2Ccyrillic-ext%2Cgreek-ext%2Cgreek%2Cvietnamese&amp;ver=3.7.3" type="text/css" media="all">




    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= stylesheet_link_tag "reset", :media => "all" %>
    <%= stylesheet_link_tag "wp_style", :media => "all" %>
    <%= stylesheet_link_tag "custom", :media => "all" %>
    <%= stylesheet_link_tag "jquery-ui-1.10.4.min.css" %>
    <link rel="stylesheet" id="googlefonts-css" href="http://fonts.googleapis.com/css?family=Open+Sans%3A400%2C600%2C700%7COpen+Sans+Condensed%3A300%2C700%7COswald%3A300%2C400%2C700%7CAlegreya%3A400&amp;subset=latin%2Clatin-ext%2Ccyrillic%2Ccyrillic-ext%2Cgreek-ext%2Cgreek%2Cvietnamese&amp;ver=3.7.3" type="text/css" media="all">

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
    <%= javascript_include_tag "application" %>
  </head>
  <body>
    <div id="site">
      <div id="wrapper">
        <div id="header-wrapper">
          <div id="top-header-wrapper">
            <div id="top-nav">
              <div class="menu-top-container">
                <ul id="menu-top" class="menu">
                  <li id="menu-item-1097" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1097">
                    <a href="http://www.sharpnation.com/become-writer/">Write For SharpNation</a>
                  </li>
                </ul>
              </div>
            </div><!--top-nav-->
            <div id="content-social">
              <ul>
                <li><a href="http://www.facebook.com/sharpnation" alt="Facebook" class="fb-but" target="_blank"></a></li>
                <li><a href="http://www.twitter.com/SharpNationNews" alt="Twitter" class="twitter-but" target="_blank"></a></li>
                <li><a href="https://plus.google.com/+sharpnation" alt="Google Plus" class="google-but" target="_blank"></a></li>
                <li><a href="http://www.sharpnation.com/feed/rss/" alt="RSS Feed" class="rss-but"></a></li>
              </ul>
            </div><!--content-social-->
          </div><!--top-header-wrapper-->
          
          <div id="logo-wrapper" itemscope="" itemtype="http://schema.org/Organization">
            <a itemprop="url" href="assets/Free Sports Picks -.html"><img itemprop="logo" src="<%= asset_path('sharpnation.png')%>" alt="Free Sports Picks"></a>
            <form action="#" class="aright" id="login_form">
              <div class="box aleft">
                <span>Username:</span><br/><input type="text" id="username" name="username" value=""/>
              </div>
              <div class="box aleft">
                <span>Password:</span><br/><input type="password" id="password" name="password" value=""/>
              </div>  
              <input type="submit" value="Login" class="login" onclick="return false;" />
            </form>
          </div><!--logo-wrapper-->
        </div><!--header-wrapper-->
        
        <div id="nav-wrapper">
          <%= render :partial => "layouts/menu" %>
        </div><!--nav-wrapper-->
        <div id="main">
        
          <div id="content-wrapper">
            <div id="home-main">

            <%= yield %>


            </div><!--home-main-->
            <div id="sidebar-wrapper">
              <ul>
                <li class="sidebar-widget">
                  <span class="sidebar-widget-header"><h3 class="sidebar-widget-header">Premium Picks</h3></span> <div class="textwidget">
                    <center>
                      <a href="http://www.sharpnation.com/premium-pick.html"><img src="<%= asset_path('premium-link-generator-website-150x150.jpg') %>" alt="Smiley face" width="150" height="150" class="hoverZoomLink">
                      </a>
                    </center>
                  </div>
                <a href="/premium_picks"></a>
                </li>
              </ul>
            </div><!--sidebar-wrapper-->
          </div>
        </div>
      </div>
    </div>  
  </body>
</html>

app/views/layouts/_menu.html.erb
<ul class="main-nav">
  <div class="menu-menu-1-container">
    <ul id="menu-menu-1" class="menu">
      <li id="menu-item-24" class="menu-item menu-item-type-custom menu-item-object-custom current-menu-item current_page_item menu-item-home menu-item-24"><a href="/">Home</a></li>
      <li id="menu-item-26" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-has-children menu-item-26"><a href="/events/nba/">NBA</a></li>
      <li id="menu-item-27" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-27"><a href="/mlb">MLB</a></li>
<!--                 <li id="menu-item-773" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-has-children menu-item-773"><a href="http://www.sharpnation.com/ncaa-football-picks/">NCAA</a>
      <ul class="sub-menu">
        <li id="menu-item-1744" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-1744"><a href="http://www.sharpnation.com/college-basketball/">College Basketball</a></li>
      </ul>
      </li>
-->                
      <li id="menu-item-1846" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-1846"><a href="/premium_picks">Premium Picks</a></li>
<!--       <li id="menu-item-1114" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1114"><a href="#">Write For Us</a></li> -->
    </ul>
  </div>
</ul><!--main-nav-->
<div id="nav-mobi">
  <div class="menu-menu-1-container">
    <select>
      <option value="#">Menu</option>
      <option value="/" selected="">Home</option>
      <option value="/events/nba/">NBA</option>
      <option value="/mlb">MLB</option>
      <option value="/premium_picks">Premium Picks</option>
<!--       <option value="#">Write For Us</option> -->
    </select>
  </div>
</div><!--nav-mobi-->

<div id="main-search">
  <form method="get" id="searchform" action="assets/Free Sports Picks -.html">
    <input type="text" name="s" id="s" value="Search" onfocus="if (this.value == &quot;Search&quot;) { this.value = &quot;&quot;; }" onblur="if (this.value == &quot;&quot;) { this.value = &quot;Search&quot;; }">
    <input type="hidden" id="search-button">
  </form>
</div><!--main-search-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <%= display_meta_tags %>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "SportsOdds" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= stylesheet_link_tag "jquery-ui-1.10.4.min.css" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/">SportsOdds</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <li><%= link_to "NBA", nba_events_path  %></li>
              <li><%= link_to "MLB", mlb_events_path  %></li>
              <li><%= link_to "Espn Games", espn_games_path  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "#"  %></li>
              <li><%= link_to "Link2", "#"  %></li>
              <li><%= link_to "Link3", "#"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2014</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>